services:
  db:
    image: mariadb:11
    container_name: easydigital-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - wp_db_data:/var/lib/mysql
    networks:
      - wp_internal

  wordpress:
    image: ghcr.io/danieleramacci/sito-easydigital:latest
    container_name: easydigital-wordpress
    depends_on:
      - db
    restart: unless-stopped
    pull_policy: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      - wp_data:/var/www/html
    labels:
      - traefik.enable=true

      - traefik.http.routers.easydigital.rule=Host(`${WP_DOMAIN}`)
      - traefik.http.routers.easydigital.entrypoints=web
      - traefik.http.middlewares.easydigital-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.easydigital.middlewares=easydigital-https-redirect

      - traefik.http.routers.easydigital-secure.rule=Host(`${WP_DOMAIN}`)
      - traefik.http.routers.easydigital-secure.entrypoints=websecure
      - traefik.http.routers.easydigital-secure.tls.certresolver=myresolver
      - traefik.http.services.easydigital.loadbalancer.server.port=80

      - traefik.http.middlewares.easydigital-sec-headers.headers.stsSeconds=31536000
      - traefik.http.middlewares.easydigital-sec-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.easydigital-sec-headers.headers.stsPreload=true
      - traefik.http.middlewares.easydigital-sec-headers.headers.browserXssFilter=true
      - traefik.http.middlewares.easydigital-sec-headers.headers.contentTypeNosniff=true
      - traefik.http.routers.easydigital-secure.middlewares=easydigital-sec-headers
    networks:
      - wp_internal
      - gruppo_proxy

networks:
  wp_internal:
  gruppo_proxy:
    external: true
    name: gruppo_proxy

volumes:
  wp_data:
  wp_db_data:
